---
- job:
    name: myjob-noop
    parent: base
    description: This a noop job
    run: playbooks/noop.yaml
    nodeset:
      nodes:
        - name: test-node
          label: centos-oci

- project:
    name: morucci/repopo1
    check:
      jobs:
        - myjob-noop
        - demo-rpmbuild
