---
- job:
    name: myjob-noopl
    parent: base
    description: This a noop job
    run: playbooks/noop.yaml
    required-projects:
      - morucci/repopo1
    nodeset:
      nodes:
        - name: test-node
          label: runc-centos
          
- project:
    check:
      jobs:
        - myjob-noopl
    gate:
      jobs:
        - myjob-noopl
