---
- job:
    name: myjob-noope
    parent: base
    description: This a noop job
    run: playbooks/noop.yaml
    required-projects:
      - morucci/repopo1
#      - morucci/repopo2
    nodeset:
      nodes:
        - name: test-node
          label: centos-oci
          
- project:
    name: morucci/repopo1
#    check-github.com:
    post:
      jobs:
        - myjob-noope
#        - myjob-noop2
#    gate-github.com:
#      queue: repopo-integrated
#      jobs:
#        - myjob-noop
